### ISSUE TITLE
Opaque error when current-input-port is not attached fd

### ISSUE THREAD

**Issue by samdphillips** [smitchell556/get-pass#1]
If `get-pass` isn't getting data from an fd it should probably error or just `read-line`.

```
Welcome to Racket v7.8 [cs].
> ,r get-pass
> (get-pass)
; apply: bad value for conversion
;   ctype: _int32
;   value: #f
; [,bt for context]
```

**Comment by spenceforce** [comment]
Hmm odd. It's supposed to use the current input port if one isn't provided. It does use `read-line` to read from the input port. Based on the backtrace, it looks like it's not a file descriptor problem but something with a ctype value. I'll try to replicate.

Can you give me your OS?

**Comment by samdphillips** [comment]
I'm on Linux.

I get the same error if I do:
```
(with-input-from-string "test" (lambda () (get-pass)))
```

**Comment by spenceforce** [comment]
Ok, it will raise an error if it cannot get a file descriptor for `in`. I doubt `with-input-from-string` will work since it probably doesn't make a file descriptor as it's just text. Ports and file descriptors are similar, but not equivalent. It's meant to be used from scripts where `current-input-port` is stdin, not the racket REPL. I can't say for sure, but the REPL has control of stdin, so it may not actually pass that on to `current-input-port` which would explain the error here. From a simple racket script `get-pass` works no problem.
